name: Test Google Drive Model Download

on:
  workflow_dispatch:

jobs:
  test_download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode rclone config
        run: |
          echo "$GDRIVE_RCLONE_B64" | base64 --decode > rclone.conf
        env:
          GDRIVE_RCLONE_B64: ${{ secrets.GDRIVE_RCLONE_B64 }}

      - name: Install rclone
        run: |
          sudo apt-get update && sudo apt-get install -y rclone

      - name: Test download model file from Google Drive
        run: |
          mkdir -p ./model
          rclone --config ./rclone.conf copy deepseek-drive:models/DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf ./model -P

      - name: List downloaded files
        run: |
          ls -lh ./model

      - name: Check if model file exists
        run: |
          if [ ! -f ./model/DeepSeek-R1-0528-Qwen3-8B-Q4_K_M.gguf ]; then
            echo "Model file not found!"
            exit 1
          else
            echo "Model file downloaded successfully."
          fi
